# config.py

SERVER_HOST = 'localhost'
SERVER_PORT = 8888
TCP_CHAT_PORT = 8889
UDP_FILE_PORT = 8890
BUFFER_SIZE = 4096
FILE_CHUNK_SIZE = 1024

# Protocol Messages
PEER_LIST_REQUEST = "GET_PEERS"
PEER_REGISTER = "REGISTER"
PEER_UNREGISTER = "UNREGISTER"
FILE_TRANSFER_START = "FILE_START"
FILE_TRANSFER_CHUNK = "FILE_CHUNK"
FILE_TRANSFER_END = "FILE_END"
